### ISSUE TITLE
Reported Cost (EDP) was inf.

### ISSUE THREAD

**Issue by derange-alembic** [kartik-hegde/mindmappings#2]
Dear authors, thanks for this tool! However, when I followed the [setup instructions](https://github.com/kartik-hegde/mindmappings#to-get-started-follow-the-below-steps) and executed `python3 costModel/timeloop/model_timeloop.py`, it reported the EDP to be `inf` as below, is it an expected (or possible) outputs ? If not, how could this be fixed ?

![image](https://user-images.githubusercontent.com/16973185/166183184-168f7d8a-1154-4f88-bd8a-88014ca36ee2.png)

**Comment by derange-alembic** [comment]
Never mind I didn't set up Accelergy tables correctly.

**Comment by kartik-hegde** [comment]
Thanks for posting this. Yes, inf can come when the timeloop library is not correctly set.

Improving the error message may be helpful here.
